### ISSUE TITLE
ModuleNotFoundError: No module named 'geomdl.shapes'

### ISSUE THREAD

**Issue by Batmanabcdefg** [orbingol/geomdl-shapes#1]
**ModuleNotFoundError: No module named 'geomdl.shapes'**

```
pip install --user geomdl.shapes
Requirement already satisfied: geomdl.shapes in ./.local/lib/python3.7/site-packages (1.2.0)
Requirement already satisfied: geomdl>=5.2.0 in ./anaconda3/lib/python3.7/site-packages (from geomdl.shapes) (5.2.8)
```

**Comment by orbingol** [comment]
I understand that you are trying to say that when you import geomdl-shapes module using `from geomdl import shapes`, you get `ModuleNotFoundError` exception. It seems that you installed geomdl-shapes and geomdl in different `PYTHON_PATH`s. This problem is related to your python installation (or scripts running during terminal session startup to initialize variables related to python/Anaconda).

If you are using Anaconda, make sure that you have switched to the correct environment (base or other). Please refer to [conda documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) for more details. If you are using system python interpreter, make sure that you have installed all required packages to the correct path. Please refer to the [pip documentation](https://pip.pypa.io/en/stable/user_guide/) for more details.

Alternatively, you can update/fix the `PYTHON_PATH` environmental variable.
